### PR TITLE
fix: Fix unpredictable false positive/negative of missing entity access check in function scope due to cache key conflict

### LINKED ISSUE #475: Random false positive "Missing explicit access check on entity query"
I've been hitting some issues for a month or so where randomly after switching a branch I would see several "Missing explicit access check on entity query" reported. However, they're all fine and fixed. I would move the accessCheck() call around and then run again and the error would vanish. I would put the line back to the original and it wouldn't fail anymore it would be like a ghost that's now gone.

Push forward to now, and we upgraded PHPStan and went from 1.1.20 phpstan-drupal to 1.1.25 and now we have 6 false positives in our CI which won't go away. No matter what we do with the accessCheck call they report. And if we checkout the exact same code version and run PHPStan we get zero errors. So we seem to be seeing different results depending on where it runs - somewhat similar to before where random people would get random failures and it would just disappear - but instead it's now on the CI, no longer random, and completely reproducing every time. CI is GitHub Actions hosted so ephemeral. We just can't get the PHPStan to pass anymore. Locally, we get 0 errors and cannot get them to appear. I managed to get them once but they vanished on the second run, but no luck since.

Can't rule out something really weird in our configuration but I've yet to find it. The only difference I haven't explored in detail is GitHub Actions is using Ubuntu and I am using macOS.

It's only ever been a problem with this specific error though.

### PR DESCRIPTION
**Pull request by driskell**
Fixes #475

The EntityQueryType was getting cached in function scope for a `condition` call and because it wasn't handled by dynamic return it reused. So if you had `condition` before `accessCheck` and then later on after it, the latter one could fail because it would return the cached without access check and there would be no subsequent access check (it happens before).

Added test case.

Still examining why this doesn't occur in class scope but it seems phpstan has additional cache key when it is just not sure of its granularity.

### CODE REVIEW

**Comment by driskell** [comment]
It did happen in class scope - PR has tests for both that reproduce and the fix solve

**Comment by mxr576** [comment]
Tested the fix on those false positives that we got reported and the patch did silence them. RTBC

(The pipeline looks broken at this moment, I made an attempt to fix one issue in #485, but other skeletons popped up.)

File: src/Type/EntityQuery/EntityQueryType.php [hunk 1]
```diff
@@ -22,4 +22,9 @@ public function withAccessCheck(): self
 
         return $type;
     }
+
+    protected function describeAdditionalCacheKey(): string
+    {
+        return $this->hasAccessCheck ? 'with-access-check' : '';
+    }
```
Comment (mglaman) [inline src/Type/EntityQuery/EntityQueryType.php:29]: Should we make sure that we has `without-access-check` as the other option for verbosity?

File: tests/src/Rules/EntityQueryHasAccessCheckRuleTest.php [hunk 2]
```diff
@@ -86,5 +86,15 @@ public function cases(): \Generator
...
+
+        yield 'bug-475.php' => [
+            [__DIR__.'/data/bug-475.php'],
+            []
+        ];
+
+        yield 'bug-475b.php' => [
+            [__DIR__.'/data/bug-475b.php'],
+            []
+        ];
```
Comment (mglaman) [inline tests/src/Rules/EntityQueryHasAccessCheckRuleTest.php:98]: The tests are failing on these:

```
'17: Missing explicit access check on entity query.
    💡 See https://www.drupal.org/node/3201242
```

**Review by mglaman — COMMENTED** [review]
I think I found the problem. It is in `\mglaman\PHPStanDrupal\Type\EntityQuery\EntityQueryType::withAccessCheck` because we clone the object, which has a cached description key. This is definitely a fix, but we need to stop cloning, as it copies the `cachedDescription`

File: src/Type/EntityQuery/EntityQueryType.php [hunk 3]
```diff
@@ -17,9 +17,17 @@ public function hasAccessCheck(): bool
 
     public function withAccessCheck(): self
     {
-        $type = clone $this;
+        $type = new self(
+            $this->getClassName(),
+            $this->getSubtractedType(),
+            $this->getClassReflection()
+        );
         $type->hasAccessCheck = true;
```
Comment (mglaman) [inline src/Type/EntityQuery/EntityQueryType.php:25]: cc @brambaud since you contributed this code. I didn't think twice when we first added this, but cloning was copying over cached information, leading to the bugs.

Comment (mglaman) [reply src/Type/EntityQuery/EntityQueryType.php:25]: :/ looks like this caused more failures although it fixed the one bug. Probably because I used `self` instead of `static`.

**Comment by driskell** [comment]
@mglaman Thanks! I read the two commits and they definitely improvements :)

Really happy this got in - it was a super hard one to track down!!!

**Comment by mglaman** [comment]
> Really happy this got in - it was a super hard one to track down!!!

Thanks for tracking this down! It was driving me wild.

File: src/Type/EntityQuery/EntityQueryType.php (hunk 3 above)
Comment (brambaud) [reply src/Type/EntityQuery/EntityQueryType.php]: Hooo! 😮 
Nice catch! Didn't think of that! 🙇
