### PR TITLE
Make it possible to opt out of loading api.php files

### LINKED ISSUE #640: Including api.php in DrupalAutoloader throws PHP redeclare error
# Bug report

In the latest 1.2.3, changes were made to the `DrupalAutoloader.php` to include `.api.php` files: https://github.com/mglaman/phpstan-drupal/commit/446a99004db28b5d711d9e834f0818c427f5be40

This causes a PHP error we can't fix or ignore because it's between the core `field` module and the contrib `tmgmt_content`. Both modules include the same hook example in their API file so requiring those files will throw a PHP Fatal error.

```
PHP Fatal error:  Cannot redeclare hook_field_info_alter() (previously declared in /projects/site/web/core/modules/field/field.api.php:53) in /projects/site/web/modules/contrib/tmgmt/sources/content/tmgmt_content.api.php on line 47
Fatal error: Cannot redeclare hook_field_info_alter() (previously declared in /projects/site/web/core/modules/field/field.api.php:53) in /projects/site/web/modules/contrib/tmgmt/sources/content/tmgmt_content.api.php on line 47
```

### PR DESCRIPTION
**Pull request by eiriksm**
This makes it possible to opt out of loading api.php files, which can be something you want if you are experiencing the issue described in #640 

I tried to add a test for this as well, but since we have a test that requires us to scan for the file, adding it to a file in the fixture dir would make other tests fail :) I guess we could move some files in there as part of ::setup and then remove them in ::teardown or something. But feels hacky. Open to adding it, if adding test coverage would make this merged ;)

fixes #640

### CODE REVIEW

File: src/Drupal/DrupalAutoloader.php [hunk 1]
```diff
@@ -112,7 +112,8 @@ public function register(Container $container): void
                 $this->loadAndCatchErrors($module_dir . '/' . $module_name . '.post_update.php');
             }
             // Add .api.php
-            if (file_exists($module_dir . '/' . $module_name . '.api.php')) {
+            $opt_out_of_api_php_scanning = isset($drupalParams['opt_out_api.php']) && (bool) $drupalParams['opt_out_api.php'] === true;
+            if (!$opt_out_of_api_php_scanning && file_exists($module_dir . '/' . $module_name . '.api.php')) {
                 $this->loadAndCatchErrors($module_dir . '/' . $module_name . '.api.php');
```
Comment (mglaman) [inline src/Drupal/DrupalAutoloader.php:117]: Technically, it will always be set due to schema and defaults. Can `opt_out_of_api_php_scanning` be defined outside of the `foreach` loop.

File: extension.neon [hunk 2]
```diff
@@ -233,6 +234,7 @@ parameters:
 parametersSchema:
 	drupal: structure([
 		drupal_root: string()
+		opt_out_api.php: boolean()
```
Comment (mglaman) [inline extension.neon:237]: I'd like to change this to:

```
bleedingEdge: structure[
	checkDeprecatedHooks: boolean()
])
```

Then the default is

```
drupal_root: '% currentWorkingDirectory%'
bleedingEdge:
	checkDeprecatedHooks: false
```

**Review by mglaman — COMMENTED** [review]
Some thoughts. I can make the changes later in my afternoon. But noting them here in case you have bandwidth.

**Comment by eiriksm** [comment]
Alrighty, I changed it up now. Still unsure how you would use the bleeding edge concept, so no logic for that is applied here

**Comment by eiriksm** [comment]
Right, now the test added for the api.php functionality fails, but I am sure you can rework or remove that somehow? I will leave in ~30 mins, so feel free to take over :v:

**Comment by mglaman** [comment]
99% tests include this config file https://github.com/mglaman/phpstan-drupal/blob/main/tests/fixtures/config/phpunit-drupal-phpstan.neon so it can be turned on there

I'll poke at this later, thanks for the changes!

File: extension.neon [hunk 3]
```diff
@@ -233,6 +235,9 @@ parameters:
 parametersSchema:
 	drupal: structure([
 		drupal_root: string()
+		bleedingEdge: structure([
+			checkDeprecatedHooks: boolean()
+		])
```
Comment (mglaman) [inline extension.neon:240]: I want to rename this about "loading API files to check for deprecated hooks" so we can keep the rule and enable configured deprecated hooks manually

File: bleedingEdge.neon [hunk 4]
```diff
@@ -0,0 +1,4 @@
+parameters:
+	drupal:
+		bleedingEdge:
+			checkDeprecatedHooks: true
```
Comment (mglaman) [inline bleedingEdge.neon:4]: File needs to be documented

File: src/Rules/Deprecations/DeprecatedHookImplementation.php [hunk 5]
```diff
@@ -46,6 +43,36 @@ public function processNode(Node $node, Scope $scope) : array
...
+                )->build()
+            ];
+        }
+        if (str_starts_with($hook_name, 'hook_field_widget_multivalue_') && str_ends_with($hook_name, '_form_alter')) {
+            return [
+                RuleErrorBuilder::message(
+                    "Function $function_name implements $hook_name which is deprecated in drupal:9.2.0 and is removed from drupal:10.0.0. Use hook_field_widget_complete_WIDGET_TYPE_form_alter instead.",
+                )->build()
+            ];
+        }
```
Comment (mglaman) [inline src/Rules/Deprecations/DeprecatedHookImplementation.php:74]: This needs a refactor. Ideally, it would be a better format as a static array in a helper method.

File: bleedingEdge.neon (hunk 4 above)
Comment (mglaman) [reply bleedingEdge.neon]: It can be done later: https://github.com/mglaman/phpstan-drupal/issues/644

File: tests/src/Rules/DeprecatedHookImplementationTest.php [hunk 6]
```diff
@@ -35,6 +35,18 @@ public function testRule() : void {
...
+            [
+                'Function deprecated_field_widget_hooks_field_widget_form_alter implements hook_field_widget_form_alter which is deprecated in drupal:9.2.0 and is removed from drupal:10.0.0. Use
+  hook_field_widget_single_element_form_alter instead.',
+                5
+            ],
+            [
+                'Function deprecated_field_widget_hooks_field_widget_textfield_form_alter implements hook_field_widget_WIDGET_TYPE_form_alter which is deprecated in drupal:9.2.0 and is removed from drupal:10.0.0. Use hook_field_widget_single_element_WIDGET_TYPE_form_alter instead.',
+                9
+            ]
+        ]);
```
Comment (mglaman) [inline tests/src/Rules/DeprecatedHookImplementationTest.php:49]: This should only run on `> 9 && < 10`

**Review by mglaman — APPROVED** [review]
