### PR TITLE
Fix remaining test and analysis errors

### LINKED ISSUE #222: Undefined array key "class" in ServiceMap
Hi, I am getting the message below when trying to run PHPStan on Drupal core, out there at https://www.drupal.org/project/drupal/issues/3178534.

```
17:55:49 cd ${SOURCE_DIR}/core && sudo -u www-data ../vendor/bin/phpstan analyze
17:55:50 Note: Using configuration file /var/www/html/core/phpstan.neon.dist.
17:55:51 PHP Warning:  Undefined array key "class" in /var/www/html/vendor/mglaman/phpstan-drupal/src/Drupal/ServiceMap.php on line 41
17:55:51 Warning: Undefined array key "class" in /var/www/html/vendor/mglaman/phpstan-drupal/src/Drupal/ServiceMap.php on line 41
```

Looking at the code,

```

            if (!isset($serviceDefinition['class'])) {
                if (isset($serviceDefinition['alias'], $drupalServices[$serviceDefinition['alias']])) {
                    $serviceDefinition['class'] = $drupalServices[$serviceDefinition['alias']]['class'];
                } else {
                    continue;
                }
            }
```

seems a legit bug when `$drupalServices[$serviceDefinition['alias']]` is missing the 'class' key, there is no earlier check about that case.

### PR DESCRIPTION
**Pull request by mglaman**
Fixes #222

### CODE REVIEW

File: src/Drupal/ServiceMap.php [hunk 1]
```diff
@@ -7,51 +7,51 @@
...
-                    $serviceDefinition['class'] = $drupalServices[$serviceDefinition['alias']]['class'];
+                    $aliasedService = $drupalServices[$serviceDefinition['alias']];
+
+                    if (isset($aliasedService['class'])) {
+                        $serviceDefinition['class'] = $drupalServices[$serviceDefinition['alias']]['class'];
+                    } elseif (class_exists($serviceDefinition['alias'])) {
+                        $serviceDefinition['class'] = $serviceDefinition['alias'];
+                    }
+                } elseif (class_exists($serviceId)) {
+                    $serviceDefinition['class'] = $serviceId;
```
Comment (mglaman) [inline src/Drupal/ServiceMap.php:41]: These changes would fix https://github.com/mglaman/phpstan-drupal/issues/222, it should be spun out into a new fix if this PR cannot land easily.
