### PR TITLE
Fixes for InspectorTypeExtension

### LINKED ISSUE #852: Inspector type specifier breaks subsequent calls after Inspector
# Bug report

See https://www.drupal.org/project/project_browser/issues/3518231

### Code snippet that reproduces the problem

```php
   * @param array $images
   *   Images of the project. Each item needs to be an array with two elements:
   *   `file`, which is a \Drupal\Core\Url object pointing to the image, and
   *   `alt`, which is the alt text.
```

```php
    assert(
      Inspector::assertAllArrays($images) &&
      Inspector::assertAll(fn (array $i): bool => $i['file'] instanceof Url, $images) &&
      Inspector::assertAllHaveKey($images, 'alt')
    ) or throw new \InvalidArgumentException('The project images must be arrays with `file` and `alt` elements.');
```

https://git.drupalcode.org/project/project_browser/-/blob/2.0.x/src/ProjectBrowser/Project.php?ref_type=heads#L63

### PR DESCRIPTION
**Pull request by mglaman**
fixes #852

### CODE REVIEW

File: src/Type/InspectorTypeExtension.php [hunk 1]
```diff
@@ -104,13 +103,13 @@ private function specifyAssertAll(MethodReflection $staticMethodReflection, Stat
...
 
-        if (!$callableInfo instanceof ClosureType) {
+        if (!$callableInfo->isCallable()->yes()) {
             return new SpecifiedTypes();
         }
 
         return $this->typeSpecifier->create(
             $node->getArgs()[1]->value,
-            new IterableType(new MixedType(true), $callableInfo->getReturnType()),
+            new IterableType(new MixedType(true), new MixedType()),
```
Comment (mglaman) [inline src/Type/InspectorTypeExtension.php:112]: Should this be:

```suggestion
            new IterableType(new MixedType(true), new MixedType(true)),
```

File: src/Type/InspectorTypeExtension.php [hunk 2]
```diff
@@ -234,9 +233,9 @@ private function specifyAssertAllHaveKey(MethodReflection $staticMethodReflectio
             $keyTypes[] = new HasOffsetType(new ConstantStringType($key));
         }
 
-        $newArrayType = new ArrayType(
+        $newArrayType = new IterableType(
             new MixedType(true),
-            new ArrayType(TypeCombinator::intersect(new MixedType(), ...$keyTypes), new MixedType(true)),
+            new ArrayType(TypeCombinator::union(new MixedType(), ...$keyTypes), new MixedType(true)),
```
Comment (mglaman) [inline src/Type/InspectorTypeExtension.php:238]: Intersect gives us `hasOffset` but it's lost in `union`... maybe because we keep `MixedType` or `MixedType` is not `true`? If we have `HasOffsetType` of string... can we even have `MixedType` anymore?

So 

```
$keyTypes[] = new IntegerType();
$keyTypes[] = new StringType();

new ArrayType(TypeCombinator:: intersect(...$keyTypes), new MixedType(true)),
```

File: tests/src/Type/data/bug-852.php [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+
+    assert(Inspector::assertAllHaveKey($baz, 'alt'));
+    assertType('array<mixed, array<mixed, mixed>>', $baz);
+}
+
+function bar(array $zed): void {
+    assert(Inspector::assertAll(fn (string $value) => $value === 'foo', $zed));
+    assertType('array<mixed, string>', $zed);
+
+}
```
Comment (mglaman) [inline tests/src/Type/data/bug-852.php:23]: I'd like this to prove `hasOffset`, but we could merge and make it a follow up.

File: src/Type/InspectorTypeExtension.php (hunk 2 above)
Comment (mglaman) [reply src/Type/InspectorTypeExtension.php:238]: Removing `MixedType` still causes `'*NEVER*`

File: src/Type/InspectorTypeExtension.php (hunk 1 above)
Comment (Niklan) [reply src/Type/InspectorTypeExtension.php]:
```suggestion
            new IterableType(new MixedType(), new MixedType()),
```

I think it should be this. I'm not sure exactly, because this was my first (and only for now) extension, but it looks like the only difference between explicit Mixed and implicit is the use of that value "as boolean" (`\PHPStan\Rules\BooleansInConditions\BooleanRuleHelper::passesAsBoolean`).

If I understand it correctly, it reads as: if the mixed type is not marked as explicit, then it can be used as a boolean indicator (at users risk).

```php
$mixed_var = something_that_returns_mixed();

// This is allowed if NOT explicit.
// But if it IS explicit, it is forbidden to use as boolean?
if ($mixed_var) {}
```

So, the use of explicit mixed values in conditions should lead to an error:

```
Only booleans are allowed in an if condition, %s given.
```

I've did a very dirty check `src/test.php` → `phpstan analyze ./src/test.php` (temporary added `extension.neon` into `includes`):

```php
<?php

function some_array(): array {return [];}

$var = some_array();
\Drupal\Component\Assertion\Inspector::assertAll(fn (): bool => TRUE, $var);
foreach ($var as $key => $value) {
    if ($key) {}
    if ($value) {}
}
```

and got this results:


| TKey                  | TValue                | Analyze result                                                                                                                                                                                     |
| --------------------- | --------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `new MixedType()`     | `new MixedType()`     | `Only booleans are allowed in an if condition, (int\|string) given.` reported for `if ($key) {}`                                                                                                   |
| `new MixedType(true)` | `new MixedType()`     | `Only booleans are allowed in an if condition, (int\|string) given.` reported for `if ($key) {}`                                                                                                   |
| `new MixedType()`     | `new MixedType(true)` | `Only booleans are allowed in an if condition, (int\|string) given.` reported for `if ($key) {}`<br><br>`Only booleans are allowed in an if condition, mixed given.` reported for `if ($value) {}` |

Conclusions/assumptions:

- Explicit mixed on `TKey` has no effect, simply because it looks like PHPStan narrows its type to `int|string` regardless (unless explicit types are provided).
- Explicit mixed on `TValue` can have side-effects and works as I expected, or my test is wrong.

So, maybe, if we are not exactly sure whether it is mixed or not, we should not mark it as explicit. Because we can't guarantee what type it actually is, so why do we block such conditions? Maybe it is specified in PHPDoc or something like that. I read `TRUE` like this: I'm certain that this type contains mixed types of data that can't be used as a boolean condition.

For example, with `false/true`, this condition will not report an error `if ($value instanceof \Stringable) {}`, because we do not simply rely on the variable type but are narrowing it with `instanceof`.

Maybe it is for cases, when you want to force the user of extension to clearly specify types for such data. Kind of a strict mode or so.

Not sure what to do, but it sounds like remove `true` is much safer?
